### ISSUE TITLE
Cross compiling to airport extreme 6th gen

### ISSUE THREAD

**Issue by gchehab** [ipatch/theairportwiki#1]
Hey Chris,

First of all, thanks for the instructions and all your work, you have assembled very good information.

I have followed the cross compile NetBsd guide trying to create working cross compiling tools for the airport time capsule/airport extreme 6th gen device (my goal is to add some native functionalities like rsync and openvpn, perhaps give back snmpd that was stripped out from the firmware years ago) but, even if it gives apparently valid object files, the airport fails to run even a simple hello world.

The create filed had the following signature: 
```
hello: ELF 32-bit LSB executable, ARM, version 1, statically linked, for NetBSD 6.0, not stripped
```

Have tried many combinations of eabi and float point options, stripping, tunning. Have built tools both in Linux and Netbsd 6.0 running on i386.

As the airport extreme runs Netbsd 6.0, I am focusing the cross-compiling on it, but I can switch to Debian Lenny or Ubuntu if needed -- I do not think that the host is the source of this issue, however.

```
# uname -a
NetBSD airport 6.0 NetBSD 6.0 (build.kernel-target.conf) #0: Mon Apr 29 18:35:13 PDT 2019  root@xapp29.apple.com:/BuildRoot/Library/Caches/com.apple.xbs/Sources/J28/AirPortFW-79100.2/Embedded/Firmware/NetBSD/Targets/J28/release/obj/build.kernel-target.conf evbarm
```

Got the chrunchprog inside it to check its signature and got:

```
$ file ps
ps: ELF 32-bit LSB executable, ARM, version 1 (SYSV), statically linked, for NetBSD 6.0, stripped

```

The SYSV in the signature is the only relevant difference. The cpu of my unit is a Cortex-A9 r4p0, running firmware version 7.9.1

I would appreciate any inputs.

**Comment by ipatch** [comment]
I'll be frank, spending time to build utilities for NetBSD 4.x or even 6.0 seems like a total waste of time, I know that may hurt to read / hear, but that's just my humble opinion.  I built a toolchain for the AirPort Express a couple of years ago which was a total PITA, ended up setting up some docker containers to work with Debian Lenny because NetBSD 4.0 is so freaking old that Debian Lenny was the only thing I could use to build the NetBSD toolchain using the **build.sh** script for different archs such as MIPS MSB which if memory serves me correctly is the hardware configuration for the airport express 2g.

I can't remember if I setup a toolchain for the MSB arm airports I have laying around or not, as I haven't messed with them in some time.  I've had other things that I've been tending to presently ...unfortunately which limits my time for working with these devices ...unfortunately.

And I don't have access to any of the newer gen AirPorts that run NetBSD 6.0 so it's difficult to tell what your exact issue is.  Did you build your netbsd toolchain using the **build.sh** script provided the downloaded netbsd tarballs?  And NetBSD 6.0 is kind of ancient in of itself now, and getting any of those utils you specified above would be a PITA because if you wanted a recently modern version of one of the utils you'd start running into all sorts of library issues more than likely because the modern versions would use logic or link to libraries that not compatible with netbsd ≤ most two recent versions.  And then your going to run into space issues on your device even if you get those bins built your going to be frustrated with the lack space for the "OS" and I use that term loosely, as there is a reason Apple built all the bins into a single monolithic bin using crunchgen / crunchprog or whatever.  So then you'd end up probably wanting to write a driver to possible allow for mounting an external device ie. a USB drive or whatever to allocate more space for the device, then you'd soon realize more than likely you'd have to write a kernel driver for netbsd to work with your usb device etc etc, and if you've ever worked with netbsd then you'd probably realize the documentation isn't that great **IMHO** ...and i say that because there is a plethora of more documentation for GNU+Linux systems ie. video courses, blah, lbah, all sorts of goodness for understanding how linux can work with embedded systems and using linux as a embedded kernel for an OS such as this device.  There are a plethora (excuse my lack of vocab) open source embedded devices now that have great documentation for running linux and even building drivers for the systems, ie. beaglebone is the first one that comes to mind.

So all that said, i think you might know what i'm going to say next,

- you can continue to work with netbsd and go down that road, which don't let me stop you, but as someone who has been down that road 🙋‍♂️ it's a slippery uphill slope that will get even more challenging the further you go.
- begin to work on getting a open source bootloader setup on these devices, ie. uboot comes to mind, then work on getting a tangible linux kernel going on one of the devices, and then begin working on getting some of the default hardware that is part these devices working with the kernel. the kernel doesn't have be the most recent mainline kernel so pick one your comfortable working with, and even possibly getting a virtual env setup to develop locally so you're not having to work with the actual hardware itself, choose something like qemu to emulate one of these devices. **that's the route i'd go** 

...unfortunately as stated before I've been working with other things in various other domains that's difficult to stop what I'm doing and spend time to work on the tasks outlined above.  I don't mind answering a question from time to time, but I definitely do not have time for hand holding, and am especially not eager to aid with working with the building of outdated binaries for super old NetBSD versions.  However, it'd be interesting to see if any of these device could run inside an emulator preferably a recent version of QEMU to see how the existing bootloader works, and what would be needed to load a new bootloader on the device that could eventually load a linux kernel, and then take the next step from there.

If you're having difficulty with building the most basic version of a binary ie. Hello World then I think getting something like **rsync** to compile would be a very ambitious step ...just trying to be honest here, not saying it couldn't be done, but I think at the end of the day it'd be more trouble than it's worth.

I wish you the best, and _happy hacking™️_

cheers 🍩
Chris

**Comment by gchehab** [comment]
Hi Chris, 

Thanks for you input. Well, you are right, the effort might not pay off. I am giving a try just to see what is viable to do -- if it is -- I am not planing to spent much time working through it, though.  And I am taking the opportunity to know a little more about netbsd, haven't used a Bsd Unix for decades, and it has been fun, anyways.... 

And I agree that porting u-boot and linux for airport would make it more interesting, but I lack the time and the tools need for this kind of work -- without a good bench: jtag programmer, a logic analyser and some spare units. I would probably just brick my only device (still on active backup/network duty) on the  first attempt, provided I could circumvent the firmware signing requirement.

In any case, Netbsd 6.0, even outdated, was able finish building both tools and release to evbarm architecture using build.sh -- and most uncanny was that with this tools, I managed to compile some of software from the current pkgsrc tree. So perhaps chrooting a updated userland release could be feasible and relatively painless. 

The issue is that the device refuses to run the resulting binaries from this toolchain, the only thing I noticed was that there were a slight diference on the elf headers. Perhaps Apple has changed to only run its own crunchprogs or signed code -- what would make it hard to impossible to advance further in this direction.  

But, perhaps I just missed something on the gcc configuration that is required for the specific arm architecture of the device -- never compiled anything to cortex-a9 before, and in my experience, ARM opensource toolchains are tricky, have used it in the past with other SOCs.   

I would have validated the generated binaries on qemu-arm or my cubieboard 3, but could not run netbsd in any of them -- Netbsd on ARM (emulated or not) is not well documented. Linux, on the other hand runs smoothly on qemu-arm. I am still exploring it..

I was hopping that, in your previous efforts you had managed to get something compiled for the netbsd 6 breed of airport devices and could give some tips on it. 

I shall give it some more tries before moving forward, I will let you know if I make any progress noteworthy...  Thanks for you input.

cheers,
Guilherme

**Comment by ipatch** [comment]
No problem dude, and unfortunately I don't have AirPort devices that run NetBSD 6.x on hand, as all I have to work with or a couple of time capsules, a couple of airport extremes and a AirPort Express 2nd gen, all of which run some flavor of NetBSD 4.x ie. 4.0 or 4.0.1 depending on the firmware installed.

I'm pretty sure there is no "code signing" going on with these devices as you would traditionally think of in therm of iOS code signing or even macOS code signing, but if you think that could be an issue than try loading an older version of the AirPort firmware on the device, as AirPort Utility lets one load any of the available basebinary images that were release for the device.

If I were you, I'd purchase a Raspberry Pi and set that up as your access point so you could mess around with this device without bringing down your LAN ...but that's just me.

**Comment by gchehab** [comment]
Well, I figured it out. Apple had to tweak its Netbsd6 to compile specifically to armv7 as it was not supported in build.sh... My previous tries probably linked armv7 code with armv5 libraries, somehow silently.  

But the best news is that, instead of tweaking netbsd 6.0 to build for armv7 (Apple probably did it at some level), the current stable netbsd 8.1 was able to generate a working toolchain for armv7 that successfully built binaries runnable on the Airport (so far a statically linked hello world). 

However, now I have a nbmake that most likely is functional to build pkgsrc packages from the current source tree. I will now test hardware floating point support and if airport has shared libraries support enabled.

Although they are not entirely necessary, it would be nice to make my packages with those options enabled -- perhaps even add some support for prebuilt binary packages from the main pkgsrc armv7hf port. 

Thanks for all your input, it was really helpful. Might you want to add some information on airport wiki on how to build for this brand of devices, please let me know -- we can switch to regular email.

Guilherme

ps.: I actually do have also a raspberry pi at home, but hacking it for anything would be just too easy :-)  
Besides, its onboard single band wifi is no go in my building -- too much interference -- heard that the v4 has improved a lot and it already does dual band...

**Comment by ipatch** [comment]
Glad to hear you made some progress.  I'm eventually going to phase out the old mediawiki site hosted at theairportwiki.com and replace it with something a little newer, but just haven't gotten around to it.

If you want to post the steps you did to get your Hello World binary to compile and run, you can post your steps in this isse, _please use markdown formatting_ or open a PR and I'll merge your steps into this repo, or you can add a document to this repos subwiki

https://github.com/ipatch/theairportwiki/wiki

**Comment by gchehab** [comment]
Will certainly do. Haven't done yet cause I have yet to polish it up. 
Even if the compiled binaries run, they have issues like random segfaults -- they can be from incompatibilities between my compiled libc and the standard kernel... 
Still investigating to see if there is any reliable way through.

**Comment by gchehab** [comment]
Hi Chris, while I am not done with the customization I want to do yet, I got already a running copy of rsync (used to sync a filesystem with a few TB for a couple of weeks now) and some other packages compiled. 
~~I am trying to figure it out how to create a pull request to the wiki part of this project to no avail, so. I'll post the markdown of the steps taken to create the toolchain, some tips to get a full netbsd 7.2 distrib working and some pointer on how to create packages using the pkgsrc package management.~~

Just added to the wiki as 'Building A Cross Compile NetBDD toolchain for newer armv6 devices'

**Comment by ipatch** [comment]
very cool dude. 👍

I'll add you to the list of contributors of the wiki if you want to create a new markdown doc with your notes in the wiki.

And I'm not sure github wiki's support the PR system unfortunately.

**Comment by gchehab** [comment]
That's great, I will add this notes directly on the wiki.
Yeah, github wiki lacks support for PR yet.

**Comment by krackers** [comment]
I found [this other article](https://e17i.github.io/articles-timecapsule-crossbuild/) which also includes some cross compilation notes. Possibly worth including it in the wiki

Also @gchehab any thoughts on possibly hosting the pre-compiled statically linked binaries you were able to build somewhere? It'd be useful for those who don't want to go through the entire toolchain setup. Perl, bash, vi, grep, find (plus the rest of the missing coreutils) would be particularly useful for exploring further and generally scripting changes to pf and hostap configs.

**Comment by gchehab** [comment]
Hi @krackers, great I am checking this out, the package he compiled, rmt, is on the standard NetBSD, the method I used creates it by default, on the other hand, the script he used is much simpler.  

He used another arm version, and he does not mention anything about his airport, however, I am compiling again with his configuration to see how it goes. As it was for an older arm architecture version, we could expect some differences in performance and compatibility, but I had some trouble compiling for armv6hf. I had to create ugly hacks in some packets.

Regarding the packages, I will see if I still have the binary packages, had a crash in my HD a while back, I am afraid I don't, but I might have the configuration files to recreate them... 

In any case, looking for it, I just have found a way to cross-compile the packages, and that is a huge improvement since compiling natively is quite slow. If I manage to do that I might try bulk create all pkgsrc packages so we will have a binary repository.

BTW, the really best would be porting OpenWRT (or at least an updated kernel) for this unit, there is a single report of a successful Linux kernel build in GitHub from the guy who successfully decrypted the airport firmware, [https://github.com/pablomarx/airdecrypt/issues/1](https://github.com/pablomarx/airdecrypt/issues/1). Unfortunately, the author does not have its old sources either.  I would try to recreate his steps, if I had a spare unit.

**Comment by krackers** [comment]
As you mentioned it doesn't look like reverse-engineered drivers exist yet for BCM4360, which is probably going to be a bottleneck to actually using the thing as an AP even if openwrt ends up booting. Hence why the path of least resistance here is probably just porting over the rest of userspace since we can at least make use of cunrchprog's `wl` and `hostapd` to retain AP functionality.

**Comment by ipatch** [comment]
> As you mentioned it doesn't look like reverse-engineered drivers exist yet for BCM4360, which is probably going to be a bottleneck to actually using the thing as an AP even if openwrt ends up booting. Hence why the path of least resistance here is probably just porting over the rest of userspace since we can at least make use of cunrchprog's `wl` and `hostapd` to retain AP functionality.

i'm dumb so forgive my ignorance. a few years back some people worked on a reverse webcam driver for the 2013 macbok pro that would run natively in linux. and they ended up pulling in some blobs from the original driver. so is not possible to grab the packaged blobs provided by the stock firmware and just get bits you need. similar to how debian can use "non free" network drivers?

**Comment by gchehab** [comment]
Porting the rest of the userspace had some issues, the packages have to be compiled statically, and it is not currently well supported in many cases -- like many compilers and languages (I could not get any stable version of Perl or python to run).  I am giving it another run in the next weeks, perhaps there is anything that can be improved 

Anyway, you both are right, Linux porting (or even an updated netbsd kernel) would have great challenges on its own. many things may have to be worked, WIFI, SATA, USB drivers, and so on... 

By the way, incredibly enough, hostapd was one of the userspace packages I actually did manage to build some years back, the goal would be to pave the way to add WPA3 in the future... Never tested it or got it further, however...

**Comment by ipatch** [comment]
@gchehab 

not trying to highjack this issue, but im still using an older 3rd gen time capsule with the stock Apple firmware, something like 7.8.1 if memory serves me correctly.

2 of main drawbacks i have using this as my router are,

1. accessing the shared  drive inside the unit via smb is limited to v1 of the smb protocol which forces me to pin my linux machines to 5.10.x lts kernels as more recent kernels dont support v1 of the smb protocol unfortunately.
2. the drive inside my unit is limited to a 2tb drive capacity, how difficult would it be to patch the existing firmware to support disks larger than the 2tb limit?

in a perfect world it'd be nice to have the stock apl fw patched to support those 2 features/upgrades, and a have minimal openwrt implementation working for it as well as another option.

what do you think about that?

**Comment by gchehab** [comment]
For the smb, I would say if we can compile an updated samba daemon, it could replace Apple old software. It is probably feasible, I do not remember if I tried to do it.
For the 2TB limitation, that can be more difficult. I guess it depends what is the limiting factor, it can be in the kernel, the partition schema, disk block size, the filesystem used or, worst case scenario, the hardware itself.  
But it should be interesting to take a look further...  Can you send me the full boot log? And what is the filesystem it is using?

**Comment by ipatch** [comment]
> Can you send me the full boot log? And what is the filesystem it is using?

interesting, it's pretty much stock airport 3rd gen. i think i have a video or asciicast somewhere of me recording the boot sequence. unfortunatley its the only working 3rd gen time capsule i have at the moment and it's used for work during normal business hours CST. let me see what i can dig up.

**Comment by ipatch** [comment]
does this help?

https://www.youtube.com/watch?v=MxvOgd2T2nA

**Comment by gchehab** [comment]
I am not sure, It seems that the format is similar to my own 6TB disk
(512bytes/sector, HFS) did ever try a larger disk by the way? I thought
that the first 3TB units were 3rd gen.
I've seen some resources mention that NetBSD style partition tables use a
32-bit sector number, which could set the limit to 2TB.
But it seemed that this is still an issue, and we can use alternative
partitioning schemas (MBR or GPT).  But could not figure out the one used
on my unit.
I absolutely dislike the way NetBSD uses to manage hard disks, too messy...

Em seg., 2 de mai. de 2022 às 13:59, Chris ***@***.***>
escreveu:

**Comment by krackers** [comment]
> the packages have to be compiled statically, and it is not currently well supported in many cases -- like many compilers 

Are these limitations on the build side (e.g. cpython's build process not supporting statically linking) or on the OS side (I'm not familiar with BSDs, but I know that glibc hates being statically linked and anything with threading will often end up faulting).

Also @ipatch have you tried accessing via AFP (I think there are fuse clients available, although I've never tried myself)

**Comment by ipatch** [comment]
> Also @ipatch have you tried accessing via AFP (I think there are fuse clients available, although I've never tried myself)

i get better results with smb and apple has stopped supporting afp on newer macos versions if i remember correctly

**Comment by ipatch** [comment]
i purchased one of these (XGecu TL866II) little guys a while back and stuck the winbond flash chip that i removed from my spare airport express 2g and created a bin file of it.

not sure if the file would help at all, but i have it.

i could also use the same programmer to dump the contents of the 6th gen FW if that helps.

**Comment by gchehab** [comment]
We can use the dump to compare with its respective firmware update binary. It may help figure out the memory mapping and the firmware organization.  Have you [binwalk](https://github.com/ReFirmLabs/binwalk) it?
In my attempts to understand it, I have used https://github.com/pablomarx/airdecrypt to try to figure it out. It helped a little, but not enough to rebuild a usable firmware update image. 
Without a spare unit, I would not try to burn a new firmware anyways, as I still rely on my airport as my main backup unit.

**Comment by ipatch** [comment]
i have. i ran binwalk on it. the winbond chip in the airport express is a 16MB flash chip that loads the entire OS from what i can tell. after dumping chip i loaded it in ghidra and just ran the auto decompile tools on it. took a couple  of hours to run through all the analysis tools on it, then thats about where i stopped investigating with it.
